 version: '2'
 services:
   web:
     container_name: web_server
     build: .
     ports:
      - "5000:5000"
     depends_on:
      - redis
   redis:
     container_name: redis_store
     image: armhf/redis
